index/index.go

There's questionable performance benefits to running one worker per file in
parallel, since we should be limited by leveldb write speed either way. In
benchmarks, doing it serially seems to be slightly slower, but thrash the disk
way less. Disk thrashing can cause the http server latency to increase, so I
think it's worth it.

Build the index serially, rather than in parallel

---

sequins.go
sequins_test.go

Also add this to the status response for completeness.
r? @colinmarc

Expose the version in the ETag header

---

zk_watcher.go

Increasing the other sleep to 10s too

Increase zookeeper autoreconnect timer to 10s

---

blocks/block.go
blocks/block_writer.go

This was leaking file descriptors and memory.
r? @forklady42

Make sure we close block files

---

version_mux.go

Under the current behavior, sequins will 501 if asked for a version
of a dataset it doesn't have. This is great from a correctness
standpoint - it means that we can gaurantee a single sequins node
will produce a consistent view, with no version slippage - but it
means that when sharding breaks for any other reason, the results can
be pretty dramatic.
It's important to emphasize availability in this (rare) case. Most
clients don't care if they see version A -> B -> A - they just want
some data. And we return the version with the data, so clients
can independently verify they're getting the right version anyway.
This should give us a strong second line of defense against breakages.
r? @forklady42

Do our best to return data for misproxied requests

---

cluster_test.go
config.go
db.go
version_mux.go

Also, improve a test that covers the behavior.
--> from pairing this afternoon
/cc @colinmarc

Fix a bug where the version expiry timer was not resetting

---

main.go

Correctly pull in EC2 instance credentials

---

status.go

Both to do with mutable state. Paging go-haters...

Fix two status bugs

---

backend/s3_backend.go

Check length of response

---

backend/s3_backend.go

Check length of response - take 2

---

backend/s3_backend.go

We were checking CommonPrefixes, not Contents, to get the marker for
the next page in listFiles, which meant we were throwing away files
`> 999`. The cleanest way to do this is just to use ListObjectsPages.
Unfortunately, we can't also use ListObjectsPages for listDirs,
because we do a nested request thingy there.
r? @forklady42

Use ListObjectsPages to properly page keys in S3

---

backend/s3_backend.go

It's not clear why this is necessary, but we've been seeing duplicate
entries fairly often.
We should wait and see if #43 magically fixed this, though.

Manually dedupe entries when listing files in s3 

---

status.go

The 1.7 race detector caught this. We weren't doing a shallow copy of the `Nodes` map, so we we could race mutating it and dumping it out to clients.
I took the opportunity and did a minimal refactor of some janky deep-copy code we had repeated in a few places.
r? @kitchen

Prevent a data race when marshalling db statuses

---

.travis.yml

Not sure why travis auto-changed the formatting of the zookeeper download lines, but :shrug:.

Update encrypted keys.

---

doc/manual/2-2-sharding/README.md

Hi,
this merge request fixes some minor issues.
It was created with help of [Feram][repo].
If it helped to improve this repository,
please consider to [star Feram's repo][repo] to show some love! 😊
PS:
The [Feram team][feramhq] is currently working on making this technology
available for everyone. If you want to be one of the first to use it,
please sign up up for the newsletter on [feram.co].
[repo]: https://github.com/feramhq/feram
[feramhq]: https://github.com/feramhq
[feram.co]: http://feram.co

Minor Fixes

---

blocks/block_store.go

In 38274f, we made the BlockStore object a lot more dumb; in
particular, we removed any knowledge it has about which partitions are
local (that state is instead stored on the partitions object now).
That means that if we don't have the partition in the block store,
it's probably because we never got any keys for that partition, not
anything broken. This might happen if, for instance, there was a file
with no keys in the input data.
r? @scottjab

Fix a bug where 404s are turned into 500s

---

proxy_test.go

Increase sleep times in proxy tests

---

.travis.yml

Switch test credentials to a new account

---

proxy.go

Even if you cancel a request, it's still the callers responsibility to close the response Body if `http.Client.Do` returns a non-nil error. Cancelling a request while it is in the process of streaming a response merely prevents new data from being added to the response Body, but the Body itself remains open.

Close the body of any outstanding requests.

---

backend/s3_backend.go

Sequins is leaking http connections, this call might be where it is happening.
cc @jerry-stripe

Tell the body to close on exists call.

---

zk/watcher.go

Improve zookeeper error logging.

---

backend/s3_backend.go
config.go
main.go
s3_sequins_test.go

Revert "add retries to s3backend::Open function"

---

zk/watcher.go

This addresses the following race:
* thread-1 (in `run`): call `reconnect`
* thread-2: call `CreateEphemeral`
* thread-1: call `runHooks`
`CreateEphemeral` will create the node (which will succeed because thread-1 just finished connecting to zookeeper), and then add it to `ephemeralNodes`.  `runHooks` will then try to re-add the node, which will fail, triggering a zookeeper reconnection.
r? @scottjab 

Hold `w.lock` when running zk hooks.

---

zk/watcher.go

It's safe to ignore these, since `runHooks` will recreate the ephemeral
nodes and watches as soon as we've reconnected. By not ignoring these,
we were triggering "Disconnecting from zookeeper because of error" in
the `run` loop.
r? @scottjab 

Ignore ZCLOSING errors when creating ephemeral nodes and watches.

---

.gitignore

I accidentally wiped my sequins config and project file with a `git clean` let's just ignore that stuff. 
r? @jerry-stripe 

Ignore intellij projects and sequins configs.

---

status.go

Emit a metric for how long it took the db version to download.
r? @jerry-stripe 

DB load metric.

---

backend/backend.go
backend/hdfs_backend.go
backend/s3_backend.go

This adds a log line that reports how many files and how big a given database version has.
r? @jerry-stripe 

Add logging of datasets

---

build.go

I think we'll want to export compression settings to datadog so that we can potentially alert/file tickets on uncompressed data, but this gives us something to start with.

Output sequencefile header in logs.

---

doc/manual/1-5-healthchecks-and-monitoring/README.md
status.tmpl

- Add documentation about version states and the new `ACTIVE` state.
- Add links to this documentation in the sequins dashboard for better visibility.
- Clean up appearance of db list.

add documentation about state changes

---

status.go

This will let us add alerts for duplicates.
r? @jerry-stripe

Report the Shard ID on the status page

---

config.go
debug.go
debug_test.go
sequins.conf.example
sequins.go
sequins_test.go

This will let us play them back later against multiple sequins clusters. Then when we make major changes to sequins, we can verify that everything is working just as before.

Log requests

---

status.tmpl

* give dbs a fixed width so each section is consistent and scannable
* drop bold from version names so that every word on the page is not bold
r? @jerry-stripe

Small UI fixes.

---

status.go

**Summary**
Updates the replication information for a `versionStatus` on creation and allows it to be updated by calling `calculateReplicationStats` multiple times. Previously, we would only set it after collecting all of our peers which would be a problem when getting the status with `?proxy=no`.
**Motivation** 
Ensure that replication info is up to date regardless of how it is accessed.

update replication status for versionStatus struct on initialization

---

db.go

**Summary**
Emit a metric when a version is set to active in a db.
**Motivation**
This is a feature that has been asked for an is probably a useful thing to emit.

emit an event when a version is set to active in a db

---

backend/s3_backend.go
s3_sequins_test.go

**Summary**
Add the ability to handle s3 versions symlinks through the `_SYMLINK` file. When sequins encounters a version containing a `_SYMLINK` file, it will redirect all file Open and ListFiles requests to the target version as determined by what's in the `_SYMLINK` file.
**Motivation**
This will allow us to force sequins to refetch a version by creating a new version with a lexicographically greater name and a `_SYMLINK` file with the target version specified. This is a much faster method than copying S3 directories.
**Testing**
Tested against QA.

allow s3_backend to handle _SYMLINK

---

.travis.yml

We currently have some problems with our S3 test account, which won't get resolved for at least a few days, and are blocking some important PRs.

Disable S3 tests

---

version.go

Make sure (*version).close/delete is called only once. This prevents the race that causes sequins to panic when a version is being removed while the entire dataset is also being removed. In this case, close() may be called twice on different code paths. 
r? @scottjab-stripe @dusty-stripe

Close once and delete once

---

main.go
proxy.go
zk/watcher.go

- Add more zk logging
- Fix some issues zk/watcher.go
- Add a long pause detector

Add more zk logging

---

sequins.go
sequins_test.go
vendor/github.com/stripe/goforit/Dockerfile
vendor/github.com/stripe/goforit/backend.go
vendor/github.com/stripe/goforit/backend_test.go
vendor/github.com/stripe/goforit/flags.go
vendor/github.com/stripe/goforit/flags_test.go
vendor/github.com/stripe/goforit/global.go
vendor/vendor.json

Update goforit in sequins

---

debug.go

Send a count metric for every DB request. This helps to figure out what data sets are completely unused, and should probably be deleted.
* This only sends aggregate data every minute, so it's not a high load on sequins or DataDog
* In contrast to expvar metrics:
* These are typed as RATE, so they can be safely summed over time
* These aren't lossy—even a single request to a DB will be caught

Send DB request stats
