.gitignore, hdfs_sequins_test.go, index/index.go, index/index_test.go, index/manifest.go, sequins.go, sequins_test.go
When building an index, save a json file with the expected files and sizes. If
the manifest exists when we start up sequins again, load it and use the
existing index rather than building a brand new index.
r? @jpellerin
=> Add the ability to save and read manifests

.gitignore, hdfs_sequins_test.go, index/index.go, index/index_reference.go, index/index_test.go, main.go, s3_sequins_test.go, sequins.go, sequins_test.go
Previously, we didn't do any synchronization on the index, so when we upgrade to a new index, the old one just gets stomped, even if there are requests that are currently using that index.
The strategy for fixing this is as follows: we take out an RW mutex when getting a reference to the index, and bump a refcount for that mutex. When updating to a new index version, the upgrader takes out a write lock on the mutex, swaps them, release the mutex, and then waits for the refcount of the mutex to drain to 0 before destroying it. This is reasonably efficient, since we only need mutual exclusion when getting _a reference to the index_, not when actually using it. The logic for this is mostly factored away in side of the newly created IndexMonitor struct.
r? @colinmarc
=> Fix race condition when upgrading between DB versions

sequins.go
Defer semantics are hard.
I missed that when you call `s.indexReference.Replace(nil).Close()`, the
`Close()` is deferred, but not the `Replace()`.
This resulted in immediately nilling the index upon starting up the http
server, which causes the server to panic.
r? @colinmarc
=> Fix bug in cleanup code

Makefile, hdfs_sequins_test.go, s3_sequins_test.go, sequins.go, sequins_test.go
We now look at the `Accept-Encoding` header to allow the client to
request gzip encoding.
Currently, the solution only considers the request to determine the
content encoding. In the future, we may want to augment this so sequins
can reply with the identity encoding for small requests, where gzipping
the request is likely to be counter-productive.
=> Add support for gzip encoding

backend/hdfs_backend.go, backend/s3_backend.go, sequins.go
This is not very DRY, but it passes existing tests. Any suggestions for cleaning it up a bit, or adding new tests to exercise the partial download protection? Is this approach to fixing #12 ok, or do you have a different idea of how to address it?
=> Use temp dirs for downloads in progress (fixes #12)

Makefile, blocks/block_store.go, blocks/block_store_test.go, cluster_test.go, config.go, sequins.conf.example, version_builder.go, zk_watcher_test.go
The functional cluster tests were sometimes failing because the client
doing HTTP gets sometimes wasn't fast enough to catch version changes
happening under the hood. Hooray for sequins being too fast!
I had thought before about allowing users to throttle loads, for
when they have small datasets and are super sensitive about latency.
It turns out this is a nice property to have when we're testing; we
can use it to slow down loads to an observable level.
=> Add a 'throttle_loads' config property, and use it improve tests

config.go, debug.go, main.go, sequins.conf.example, sequins.go, vendor/github.com/codahale/hdrhistogram/LICENSE, vendor/github.com/codahale/hdrhistogram/README.md, vendor/github.com/codahale/hdrhistogram/hdr.go, vendor/github.com/codahale/hdrhistogram/hdr_test.go, vendor/github.com/codahale/hdrhistogram/window.go, vendor/github.com/codahale/hdrhistogram/window_test.go, vendor/manifest
This adds a few config properties for tweaking debug output, and adds
some basic sequins-specific expvars, while we're at it - QPS, latency,
and disk usage.
=> Add some rough expvars for sequins

main.go
This fixes a bug where the EC2 instance region wasn't being correctly
picked up. The problem is that `regionName, err := metadata.Region()`
instantiates a new variable because of how `:=` works with lexical
scoping.
=> Use the EC2 instance region if available

.travis.yml, Makefile, cluster_test.go, config.go, debug.go, main.go, proxy.go, proxy_test.go, sequins.conf.example, sequins.go, status.go, version.go
This is an attempt to try and minimize variance in latency without increasing load, by introducing a technique in proxying that I'm sure has a real name, but which I'm calling staged proxying.
The basic idea is this. When we need to proxy a request, and have N peers which could service that request, we can try concurrent requests if the peer we try first is being particularly slow. We use the following algorithm to dispatch requests:
- Each interval of `proxy_stage_timeout`, starting immediately, a request is kicked off to one random not-yet-tried peer. All requests after the first run concurrently.
- If a request finishes successfully to any peer, the result is returned immediately and the others are canceled, as long as the result was not an error.
- If a request finishes, but resulted …
=> Implement staged proxying

proxy.go, proxy_test.go, version.go
We were closing all open requests when returning from `proxyRequest`, but since we were returning the `http.Response` object, we ocassionally hadn't finished reading the body yet. So `ioutil.ReadAll(resp.Body)` sometimes errored with "request canceled."
r? @jbalogh (since you read the last one so thoroughly)
=> Fix a race condition in staged proxying

Makefile, cluster_test.go, zk_watcher.go, zk_watcher_test.go
The new tests caught two (minor) bugs in zkWatcher:
- `break` inside a switch statement just breaks out of the switch,
so we weren't properly closing watches on shutdown
- There was a missing `return` inside `hookWatchChildren` which was
causing the watch to 'leak'; to continue inside the loop even
when the connection to zookeeper closed. In some very specific
conditions, this could cause zkWatcher to infinitely reconnect.
- We don't need to throw away the connection when we get `STATE_CONNECTING`
- Access to `w.conn` wasn't synchronized, which lead to a possible (but extremely unlikely) data race
=> Add some zkWatcher tests, and fix some minor bugs

proxy.go, proxy_test.go, version.go
Exposes which server handled the request to the client, though a response header `X-Sequins-Proxied-To` 
To increase visibility on how many requests are proxied though sequins.  With this data we can chart if requests become slow though proxying or not. 
r @colinmarc
=> Add a response header 'X-Sequins-Proxied-To'

zk_watcher.go
If the watch was blocked on sending updates to the client process,
then it would panic trying to send on the closed `updates` chan. We can
make sure we catch `cancel`, too, with a `select`.
r? @scottjab
=> Fix a race condition when closing a watch

zk_watcher.go, zk_watcher_test.go
example demonstrates: https://play.golang.org/p/doj48elk2B
This is a real fix, whereby we let the hookWatchChildren loop close
the client channels itself, but only if it's exiting for the last
time.
This time around, I added a test for the behavior.
r? @scottjab
=> Fix a race when removing watches (for real this time)

zk_watcher.go
This was staring me in the face, once I actually went looking for it.
If we `return`ed anywhere between `w.Lock()` and `w.Unlock()` in the
`reconnect` method, we'd leak the lock, and next time around be
unable to reconnect.
r? @scottjab
=> Fix a race where we'd leak the zkWatcher reconnect lock

blocks/block_store.go, blocks/block_writer.go, build.go
In the case that we hit an error while adding files, this could leak
file descriptors; We'd close any flushed blocks, but not the ones
open for writing.
r? @kitchen
=> Close the block store if we fail to build it

blocks/block_store.go, build.go, vendor/github.com/colinmarc/sequencefile/writable.go, vendor/manifest
Hadoop does this silly key/value serialization thing where it has a serialization class for the key and for the value. In practice, that means that each key and value serialized as [BytesWritable][0] has four bytes wasted at the front for the length of it (wasted because SequenceFile length-prefixes the values too).
I realized while writing the manual that BytesWritable as the only supported key/value serialization was both arbitrary and kinda wasteful. It's [not hard][1] to write "raw" bytes for keys and values, and [Text][2] is another fairly common ["Writable"][3] that uses a single byte to length-prefix (it's actually a weird varint-like thing they call a VInt, but usually it's just one byte).
I figured we may as well support all three. It's easier than being super strict in the docs. …
=> Support hadoop.io.Text and bare values in addition to hadoop.io.BytesWritable

backend/backend.go, cluster_test.go, config.go, config_test.go, hdfs_sequins_test.go, main.go, s3_sequins_test.go, sequins.conf.example, sequins_test.go
This renames the `root` configuration option to `source`, as we discussed. It also adds a bunch of validation (and tests for the validation):
- Check that the source root and local store are absolute paths
- Check that the former doesn't contain the latter
- Make sure `file://` urls don't have a "host"
- Error on schemes other than `file://`, `hdfs://`, or `s3://`
Finally, it adds a bit of code such that relative paths work, but only from the command line.
This is best reviewed commit by commit (since the first one is just s/root/source and is pretty chunderous). r? @kitchen
=> Rename 'root' to 'source', and add a bunch of path validation

doc/manual/README.md, main.go
This allows us to be a bit more user-friendly in the tutorial; users can start up sequins without any data, and then write data to it second.
r? @kitchen
=> Allow sequins to start up without data

partitions.go, peers.go, sequins.go, zk_watcher.go, zk_watcher_test.go
Currently, we leak a non-ephemeral znode for every version of every database. This isn't *that* many, but it's kinda annoying and definitely unhygienic. 
However, we can't just go around arbitrarily deleting empty znodes, because that's racy when it comes to other nodes; they could be trying to create an ephemeral node rooted at the node we're deleting. To avoid this, this PR adds some retry logic and creating and watching that, if it needs to, also creates the parents of the nodes.
Finally, this PR fixes one possible deadlock I encountered while poking at this code.
r? @kitchen
=> Build a mechanism for GCing old zookeeper nodes

doc/manual/README.md
An example uses port `9590` when Sequins was started up on port `9599` in an earlier example.
r? @colin-stripe
=> Make port consistent throughout "Getting Started"

blocks/block.go, blocks/block_store.go, blocks/block_store_test.go, blocks/block_writer.go, blocks/hashcode.go, blocks/hashcode_test.go, blocks/manifest.go, build.go, db.go, multilock/multilock.go, multilock/multilock_test.go, partitions.go, sequins.go, serve.go, status.go, version.go
In service of trying to fix a few lurking bugs in the upgrade flows, I ended up stepping back and doing a somewhat more comprehensive refactor of the surrounding code. This PR altogether is pretty invasive, but each commit stands individually as a smaller refactor, so it hopefully shouldn't be too bad to review. We also fortunately have [pretty good functional tests](https://github.com/stripe/sequins/blob/master/cluster_test.go) for this stuff.
The fixes contained within, in ascending order of importance:
- The status webpage sometimes leaked versions, showing them as errored even after they'd been cleared.
- During startup, builds weren't respecting max_parallel_loads, which meant we could thrash the disk if a node joined a full cluster with nothing cached locally.
- Versions that were …
=> Refactor upgrade and build flows

.travis.yml, Dockerfile
We have been seeing many dns failures that look a lot like this bug:
https://github.com/golang/go/issues/16865
Sequins was running on the release version of go 1.7, this PR bumps it to the most recent stable version of go 1.7.5
r? @evan-stripe
=> Bump golang version to 1.7.5

sequins.go
When sequins proxies requests to other nodes in the cluster, it round trips to dns.  We have seen some issues with dns lookup failures when the cluster is really busy.  This will just store the peer IP addresses in ZK, which should reduce the DNS load. 
The downside is sequins _can_ lose peers, if ip addresses change it would require sequins to be restarted. 
r? @evan-stripe 
cc @bartle-stripe  @jdelaney-stripe @cff-stripe @sankari-stripe @as3richa-stripe @jbancroft-stripe @dusty-stripe @jbancroft-stripe
=> Store IP of sequins peers addresses in ZK.

db.go, doc/manual/1-1-basic-concepts/README.md, sequins.go, sequins_test.go, utils.go
We've seen problems from versions that inadvertently included special
characters (like '{'). To avoid problems, skip over anything that's
not alphanumeric.
r? @scottjab 
=> Filter out DBs and versions with invalid characters

backend/s3_backend.go, config.go, main.go, s3_sequins_test.go
Add retry functionality to the `Open` function for the s3 backend so that when calls to `GetObject` fail due to latency in updating the keys, it will be automatically handled.
cc? @wei-stripe @jbancroft-stripe @dusty-stripe @bartle-stripe @ikdc-stripe
=> add retries to s3backend::Open function

.travis.yml, Makefile, db.go, jenkins_build.sh, proxy.go, status.go, zk/watcher.go
=> Run `go vet` as part of CI, and fix all violations.

zk/watcher.go
This avoids this deadlock:
thread-1: acquire w.lock
thread-2: acquire w.hooksLock
thread-1: acquire w.hooksLock (blocks on thread-2)
thread-2: acquire w.lock (blocks on thread-1)
<deadlock>
r? @scottjab 
=> If we acquire `w.lock` and `w.hooksLock`, acquire the former first.

.travis.yml, Dockerfile
**Summary**
Upgrade the golang version to the latest stable release (1.8.3)
**Revert Plan**
`s/1.8.3/1.7.5`
=> bump golang version to 1.8.3

.travis.yml
**Summary**
This removes Mac travis CI tests.
**Motivation**
They're a pain and often fail.
=> remove mac travis tests

status.go
**Summary**
This simplifies the JSON response from `/healthcheck` to remove the hostname of the node of the version.
**Motivation**
`/healthcheck` only queries the local databases, so this remove redundant info. This also makes it a bit easier for things like the golem boxes to parse the JSON response.
**Test plan**
Automated tests
**Rollout/monitoring/revert plan**
Revert commit
=> simplify json response of healthcheck

build.go, config.go, doc/manual/1-5-healthchecks-and-monitoring/README.md, doc/manual/README.md, doc/manual/x-1-configuration-reference/README.md, sequins.conf.example, sequins.go, vendor/github.com/DataDog/datadog-go/LICENSE.txt, vendor/github.com/DataDog/datadog-go/statsd/README.md, vendor/github.com/DataDog/datadog-go/statsd/statsd.go, vendor/github.com/DataDog/datadog-go/statsd/statsd_benchmark_test.go, vendor/github.com/DataDog/datadog-go/statsd/statsd_test.go, vendor/vendor.json, version.go
**Summary**
This adds reporting to Datadog for two metrics:
1. Amount of time items take to download from S3
2. Amount of items waiting to be downloaded from S3 at a given time
**Motivation**
We currently don't have much visibility into metrics such as S3 download times or how backed up the download queue may be at any given time. This helps solve that.
**Test plan**
Automated tests
**Rollout/monitoring/revert plan**
Revert commit
=> Begin to integrate Datadog to report metrics.

build.go, sequins.go
Change the tags used for sequins reporting to datadog to be more consistent with what is currently in use.
=> tweak sequins tags

build.go, cluster_test.go, config.go, doc/manual/1-4-running-a-distributed-cluster/README.md, doc/manual/x-1-configuration-reference/README.md, sequins.conf.example, sharding/partitions.go, version.go
This prevents errors in the following case:
* A new version becomes available
* Nodes start reading the files from the new version, but some nodes are faster than others
* At some point, at least one replica of each partition exists, and the new version goes active
* Because of variable speed, many partitions still have only one replica
* A node goes down, and parts of the new version are unavailable. Clients get errors
* Eventually other nodes read enough data, and things settle down
I think my changes are roughly correct, however this is really hard to test. I have a partial test case, but I had to add some grotty code to simulate crashes, and I'm still getting sporadic failures.
r? @bartle-stripe
=> Establish a minimum replication level before switching to a new version

zk/watcher.go
This PR addresses two issues:
1. Sequins is racing the ZK server's timeouts, Sequins will timeout the goroutine before ZK times itself out.  ZK then will still be timing out when Sequins reconnects.  This doubling the timeout on the goroutine will let ZK handle the timeout of its sockets and znodes.  We should still see the timeout happen though a disconnection if this happens.  The timeout on the goroutine is mostly for thread lock safety. 
2. When sequins creates parent znodes sometimes it will fail if the parents are already created, this leads to a reconnect.  We should ignore znode exists errors when we are creating the parents.
r?  @jerry-stripe 
=> Double Sequins' timeout for ZK sessions and Ignore ErrNodeExists 

sequins.go, sharding/peers.go, sharding/peers_test.go, zk/watcher.go
Tested with the following procedure:
1. Remove `shard_id` from the configuration file
2. Restart Sequins and make sure it does smallest missing to figure out the correct `shardID`
3. Restart Sequins again and make sure it reads from the `self_assigned_id` file
4. Change the `self_assigned_id` file to be "0\n" and then restore the configuration file to include `shard_id` again
5. Restart Sequins again and make sure it uses the configuration file over the `self_assigned_id` file
I tested this on tha node with the lowest shardID, the highest shardID, and a shardID in the middle.
This has a fair amount of logging lines. Are there any you think I should remove?
=> Use smallest missing shardID if none is given

doc/manual/1-5-healthchecks-and-monitoring/README.md
By default Sequins uses port 9599 and that's the port used in all examples in the guide so for user experience we should keep it consistent.
r? @jerry-stripe
=> Change port in guide from 9590 to 9599

sharding/peers.go, status.go
This is useful information to expose to users. It's also needed so that we can write automated tests for auto-assigning shardIDs.
=> Expose node's shardID in /healthcheck

.travis.yml, cluster_test.go
Functional tests were disabled in CI almost a year ago due to flakiness (62b72b01c27ccbd7e77202b240ac8b713bb2e4d9). This refactor reenables them and address the sources of flakiness:
* There was no checking to see if Sequins actually starts up when `start` is called. This makes it possible for Sequins to randomly choose a port that's in use, fail to start up, but have the tests continue (and then fail) [0]
* Sometimes Sequins would start up too quickly and the state polling would miss states like `down`. Because this PR changes it to better control the startup process we don't need to poll for the initial `down` state.
* The `testClient` timeout was pretty low and would sometimes cause issues.
Testing this change has consisted of running the functional test suite 100 times locally and 60 …
=> Refactor functional tests and have them run again

cluster_test.go
Also changes Sequins shardID to start from 1 rather than 0 when using the config file to set the `shardID`. This better matches Sequins behavior and expectations.
cc @scottjab-stripe @bartle-stripe @dusty-stripe
=> Add functional tests for shardID auto-assignment

db.go, status.go, status.tmpl
**Summary**
- Exposes information about the status of nodes within each version.
- Modifies the front page of the dashboard to show more general information while leaving the specific information for when you click through to a database. Only the amount of nodes in a given state will be revealed for each version on the front page.
- Implement more stripey design
- Add a new `ACTIVE` state on top of the `AVAILABLE` one. An `ACTIVE` version is the one that is actively being served, and is thus a stronger statement than `AVAILABLE` which only means that it is still capable of being served by sequins. For example, the latest version might be `AVAILABLE` but not `ACTIVE` for a given node until all of its peers also mark the version as `AVAILABLE`.
**Motivation**
It's hard to tell what the …
=> redesign sequins dashboard, add version node state

blocks/block_store.go, blocks/block_writer.go
This lets downloads go several times faster on well-partitioned data. We can hit > 200 MB/s.
r? @bartle-stripe
=> Allow simultaneous adds to different partitions

status.go
The `targetReplication` field was never being used, leading to the status page replication info being a bit less useful (i.e. xxx replication: xx/0). This sets it to `min_replication` from the config. Another option is setting it to just `replication` from the config if y'all think that's preferable.
=> actually use targetReplication field in versionStatus

status.go, status.tmpl
Update the partition replication information to be a bit more clear about how many partitions are in which replication states. Also make explicit what is the average v. target replication.
=> make partition replication information a bit more clear

debug.go, serve.go
When the client cancels a request before it finishes we don't want to count that as an internal server error because it isn't. Instead we should use 499 to indicate that the client closed the request[0].
[0] Note that 499 is a nonstandard HTTP status code and not in the official spec.
cc @jerry-stripe @vasi-stripe @scottjab-stripe @dusty-stripe
=> Use status 499 when client cancels request

sequins.conf.example
The example config file is missing a line for `s3.max_retries`
cc @dusty-stripe @jerry-stripe @bartle-stripe
=> Add max_retries to example configuration file

status.tmpl
**Summary**
Makes the db name on the home page a link to it's status. Make the sequins logo a link to the homepage.
**Motivation**
The arrows were hard to click on and easy to miss.
cc? @stripe/storage 
Link:
Hover:
=> make db names links to its status, sequins logo a link to the homepage

sequins.go
The current convergence pattern isn't great. We wait to converge *twice* while holding a lock. And the lock prevents other nodes from joining. This causes a new cluster to converge on too-small a state while most nodes are blocked. This made it hard to write tests.
We can take the second wait to converge out of the lock entirely. And the first one we can shorten, since while the lock is held we can be pretty sure nodes aren't joining.
=> Shard IDs: Don't wait for convergence too much

cluster_test.go, doc/manual/2-2-sharding/README.md, sharding/partitions.go, sharding/peers.go, status.go
**Summary**
Changes the partition assignment scheme to use a sequential assignment to nodes as opposed to a hash ring. Essentially the same as https://github.com/stripe/sequins/pull/124, except keeping the Shard ID intact which is used to order nodes.
**Motivation**
Will distribute partitions amongst nodes much more uniformly.
cc? @stripe/storage 
**Note**: Tests for this will not pass until https://github.com/stripe/sequins/pull/127 is merged in as we discovered a bug in the Shard ID logic that caused tests added in this PR to fail. Leaving as WIP until it gets merged, but this has already been tested to work assuming those changes.
=> replace hash ring partition assignment with sequential scheme

status.go
Fixes the case where the `Versions` map inside the `dbStatus` struct was referred to when uninitialized. Will provide code path through comments to be more clear about how this was happening. I'm not 100% confident that this was _the_ problem, but I think this is definitely a problem.
=> initialize dbStatus with Version to prevent status page 502

zk/watcher.go
Sometimes it takes minutes for this to run.
=> Allow faster startup, by deleting ZK nodes in parallel

status.go, status.tmpl
* Show the shard ID for each node
* Show the nodes in shard-ID order
This should make things like duplicate shard IDs easier to notice.
r? @jerry-stripe
=> Display shard IDs on status page

status.go
Completely missed this in https://github.com/stripe/sequins/pull/137, but this just fixes the way we get the ShardID since it can be set by the self_assigned_id file or assigned by smallest misssing.
=> fix exposure of shard id in status page

doc/manual/2-2-sharding/README.md, sharding/partitions.go
**Summary**
Only consider unique shard IDs when choosing partition assignments.
**Motivation**
This will allow nodes to share partition assignments by using the same shard ID such that one node can replace another in the case of failure.
=> dedup shard IDs when picking local partitions

.travis.yml
**Summary**
Update the zk url, the zk version we use got moved to the archives.
**Motivation**
Travis builds have been failing with this problem: https://travis-ci.org/stripe/sequins/builds/299245524#L484
=> update zk url as the version we use got moved to archives

db.go, doc/manual/1-5-healthchecks-and-monitoring/README.md, sharding/partitions.go, status.go, status.tmpl, version.go
**Summary**
Remove the use of the `AVAILABLE` state and have the `BUILDING` state persist until `ACTIVE`. Make documentation a bit more clear as to what each state means.
**Motivation**
There has been a bit of confusion as to what each state means. Hopefully this clears some of it up.
**Testing**
Deployed to some smaller QA clusters so far, will work way up to rest of QA if all goes well.
=> remove use of versionAvailable, clarify documentation

cluster_test.go, doc/manual/1-5-healthchecks-and-monitoring/README.md, sequins.go
The fact that `/healthcheck` clashes with consul will probably cause problems later on.
=> remove /healthcheck in favor of /healthz

status.tmpl
Increase the width of the expanded db view to better accommodate the partition map.
=> increase css width some more

cluster_test.go, config.go, doc/manual/x-1-configuration-reference/README.md, sequins.conf.example, sharding/partitions.go, version.go
**Summary**
Add a new config option, `max_replication` that will limit the replication factor of partitions. For a given node, when choosing which partitions it should have locally, it will first ensure that selecting a partition wouldn't bring it over this value. If it would, it doesn't select it. `max_replication` is only respected if `max_replication <= replication`, so setting it to 0 will disable this feature.
**Motivation**
This will limit the damage of ZK flapping such that nodes don't fill up too rapidly.
**Testing**
Unit testing for now. Will test in QA as well.
=> add max_replication to config to allow for a partition replication limit

.travis.yml, Makefile
Restore S3 tests, now that we have a good S3 test account again.
Also run tests verbosely, so that we can actually tell that S3 tests are running and not skipped.
=> Restore S3 tests

sequins.go, zk/watcher.go, zk/watcher_test.go
Our service runner should then restart sequins, allowing us to successfully reconnect. Yes, this is ugly :(
Also add some extra debugging info to our ZK watcher.
=> Die if sequins is ZK-flapping

sequins.go, zk/watcher.go
The flap check isn't triggering, I think due to the time Sequins takes to start up.
* Made it 8x more aggressive
* Added logging, so we can verify that it's being used at all
=> Be more aggressive with flap-checking

backend/s3_backend.go
Trim the contents of the `_SYMLINK` file to buffer against potential whitespace when manually creating the file.
=> strip contents of _SYMLINK file

cluster_test.go, config.go, db.go, doc/manual/x-1-configuration-reference/README.md, sequins.conf.example, sequins.go, sequins_test.go, vendor/github.com/stripe/goforit/Dockerfile, vendor/github.com/stripe/goforit/README.md, vendor/github.com/stripe/goforit/examples_test.go, vendor/github.com/stripe/goforit/examples_whitebox_test.go, vendor/github.com/stripe/goforit/flags.go, vendor/github.com/stripe/goforit/flags_test.go, vendor/vendor.json
This lets Sequins start up in a mode where it only checks local disk for versions, rather than the network (mostly). It should enable rolling sequins with checking-for-new-versions off, and hence our feature flags use-case.
cc @scottjab-stripe @amith-stripe
=> Use a feature flag to control fetching versions

sequins.go, zk/watcher.go
We found in the sequins log most zookeeper errors happen because of 'node does not exist'. TriggerCleanup() is used to cleanup the old znodes for db versions that sequins nodes are no longer serving. But it takes a naive approach to deletes znodes. It just traverses the directory tree and delete the non-ephemeral znodes that can be deleted.  So there is a race condition when a znode for a new db version was just created and no partition of the db version has been downloaded by any sequins node (therefore no ephemeral nodes created in the db version znode). TriggerCleanup() can delete the db version znode right after it is created, causing all sequins nodes watching the db version znode to get 'node does not exist' error and they have to reconnect to zookeeper. The reconnecting to …
=> Serialize cleaning up znodes for old db versions and avoid a race condition

config.go, debug.go, debug_test.go, sequins.conf.example, sequins.go
We have request logging, but deploying it is a real pain in the butt on a large cluster.
Use a feature flag instead!
=> Add request logging via feature flag

config.go, debug.go, debug_test.go
Sometimes you don't want to log requests to a different log file.
=> Add support to log requests to stdout instead of a different file.

.travis.yml
Change the apache.org url in the travis config so that it pulls in zookeeper over HTTPS.
=> Update the zookeeper url to retrieve the package over TLS
